name: mdm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.7.1
  - cudatoolkit=11.0
  - numpy=1.21.5
  - scipy
  - matplotlib
  - pillow
  - tqdm
  - h5py
  - pip
  - spacy=3.3.1
  - pip:
    - trimesh
    - moviepy
    - gdown
    - wandb
    - chumpy
    - torch-cluster
    - torch-scatter
    - torch-sparse
    - torch-spline-conv
    - torch-geometric
    - smplx==0.1.28
    - fastapi
    - uvicorn
    - python-multipart
    - ftfy
    - regex
    - tqdm
    - git+https://github.com/openai/CLIP.git
    - en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.3.0/en_core_web_sm-3.3.0-py3-none-any.whl 